name: automl-streamlit-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - tensorflow
    - lightgbm
    - streamlit
    - autokeras
    - keras-tuner
    - tpot