name: automl-streamlit-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - cudatoolkit=11.2  # CUDA 버전은 사용하는 GPU와 호환되는 버전으로 선택
  - pip
  - pip:
    - tensorflow-gpu
    - lightgbm
    - streamlit
    - autokeras
    - keras-tuner
    - tpot